<?php

/**
 * @file
 * The module file of bt_basic_page.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_node_insert().
 */
function bt_basic_page_node_insert(NodeInterface $entity) {
  // Convert to lowercase, trim spaces,
  // replace spaces with underscore and then truncate to 60 chars.
  $pathTitle = substr(str_replace(" ", "-", trim(strtolower($entity->label()))), 0, 60);

  if ($entity->bundle() == 'bt_basic_page') {
    \Drupal::service('path.alias_storage')->save("/node/" . $entity->id() . '/edit', "/" . $pathTitle . '/edit', "en");
    \Drupal::service('path.alias_storage')->save("/node/" . $entity->id() . '/delete', "/" . $pathTitle . '/delete', "en");
  }

}
