<?php

/**
 * @file
 * The module file of bt_basic_page.
 */

use Drupal\node\NodeInterface;
use Drupal\path_alias\Entity\PathAlias;

/**
 * Implements hook_node_insert().
 */
function bt_basic_page_node_insert(NodeInterface $entity) {
  // Convert to lowercase, trim spaces,
  // replace spaces with underscore and then truncate to 60 chars.
  $pathTitle = substr(str_replace(" ", "-", trim(strtolower($entity->label()))), 0, 60);

  if ($entity->bundle() == 'bt_basic_page') {
    $path_alias = PathAlias::create([
      'path' => '/node/' . $entity->id() . '/edit',
      'alias' => '/' . $pathTitle . '/edit',
    ]);
    $path_alias->save();

    $path_alias = PathAlias::create([
      'path' => '/node/' . $entity->id() . '/delete',
      'alias' => '/' . $pathTitle . '/delete',
    ]);
    $path_alias->save();

    $path_alias = PathAlias::create([
      'path' => '/node/' . $entity->id() . '/latest',
      'alias' => '/' . $pathTitle . '/latest',
    ]);
    $path_alias->save();

  }

}
